services:
  - type: web
    name: oliveoshoppe
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput
    startCommand: gunicorn oliveoshoppe.wsgi:application
    envVars:
      - key: SECRET_KEY
        scope: runtime
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        scope: runtime
      - key: SUPABASE_URL
        scope: runtime
      - key: SUPABASE_ANON_KEY
        scope: runtime
      - key: SUPABASE_SERVICE_ROLE_KEY
        scope: runtime
      - key: PYTHON_VERSION
        value: "3.12"
      - key: DJANGO_SETTINGS_MODULE
        value: "oliveoshoppe.settings"
