services:
  - type: web
    name: oliveoshoppe
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: bash start.sh
    envVars:
      - key: SECRET_KEY
        scope: runtime
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        scope: runtime
      - key: DATABASE_URL
        scope: runtime
      - key: SUPABASE_URL
        scope: runtime
      - key: SUPABASE_ANON_KEY
        scope: runtime
      - key: SUPABASE_SERVICE_ROLE_KEY
        scope: runtime
      - key: PYTHON_VERSION
        value: "3.11.9"
